# MediaWiki with MySQL
version: '3'

volumes:
    images:
    data:

services:
    mysql:
        image: mysql:5.5
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: ${MYSQL_DBNAME}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            # - ./mysql_data/:/docker-entrypoint-initdb.d/
            - data:/var/lib/mysql

    mediawiki:
        build: .
        restart: always
        environment:
            MW_INSTALL_PATH: /var/www/html
            MW_SERVER: ${MW_SERVER}
            MYSQL_DBNAME: ${MYSQL_DBNAME}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MW_ADMIN_EMAIL: ${MW_ADMIN_EMAIL}
            MW_SECRET_KEY: ${MW_SECRET_KEY}
            MW_UPGRADE_KEY: ${MW_UPGRADE_KEY}
            MW_GMAPS_KEY: ${MW_GMAPS_KEY}
        ports:
            - 8080:80
        depends_on:
            - mysql
        volumes:
            - images:/var/www/html/images
